@startuml

'efcore namespace EtAlii.Generators.EntityFrameworkCore.NoBaseEntity.Tests
'efcore dbcontext SimpleEntityModelNoBaseEntityDbContextBase
'efcore interface ISimpleEntityModelNoBaseEntityDbContext

'efcore map 'From' 'Sent'
Message "1" --* "0..n" User

'efcore map 'To' 'Received'
Message "1" --* "0..n" User

'efcore map 'Tweets' 'User'
User "0..n" *-- "1" Tweet

'efcore map 'Tweet' 'Image'
Image "1" -- "0..1" Tweet

'efcore map 'Users'
class User
{
    +Id: int
    +Name: string
    -Email: string
    Sent: Message[]
    Received: Message[]
    Tweets: Tweet[]
}

'efcore map 'Messages'
class Message {
    +Id: int
    +Text: string
    From: User
    To: User
}

'efcore map 'Tweets'
class Tweet{
+Id: int
+Text: string
+User: User
Image: Image
}

'efcore map 'Images'
class Image{
+Id: int
+Data: byte[]
Tweet: Tweet
}

'note left of User::Email
'The email address of the user
'end note

@enduml
