@startuml

'efcore namespace EtAlii.Generators.EntityFrameworkCore.Tests
'efcore using EtAlii.Generators.EntityFrameworkCore.Tests.Nested
'efcore entity EntityBase
'efcore dbcontext SimpleEntityModelDbContextBase

'efcore map 'Profile' 'User'
User "1" *-- "1" Profile
'efcore map 'Message' 'Profile'
Profile "1" *-- "0..n" Message
'efcore map 'Follower' 'Profile'
Profile "1" *-- "0..n" Follower
'efcore map 'Tweet' 'Profile'
Profile "1" *-- "0..n" Tweet

Follower "1" *-- "0..n" Profile : Following
Follower "1" *-- "0..n" Profile : Followers

'efcore map 'Users'
class User
{
    +Name: string
    -Email: string
}

'efcore map 'Profiles'
class Profile
{
    +UserName: string
}

'efcore map 'Messages'
class Message {
+Text: string
}


'efcore map 'Followers'
class Follower{
+Profile: Profile
+Following: Profile[]
+Followers: Profile[]
}

'efcore map 'Tweets'
class Tweet{
+Text: string[]
+Profile: Profile
}

'note left of User::Email
'The email address of the user
'end note

@enduml
