@startuml
'namespace EtAlii.Generators.MicroMachine.Tests
'class MyNestedStateMachine1Base
'using System.Text

[*] -> State1 : Start
state State2 {
    State2 -> State2 : Check
    SubState1 -> SubState2 : Continue
}
State1 --> SubState1 : Continue
State2 --> State3 : Exit
@enduml
