@startuml
'namespace EtAlii.Generators.MicroMachine.Tests
'class MyNestedStateMachine2Base
'using System.Text

[*] -> State1 << (string name) >> : Start
State1 : this is a string
State1 : this is another string
State1 -> State2 : Continue
state State2 {
    [*] --> SubState1 : StartState2
    State2 -> State2 << (string name) >> : Check
    SubState1 -> SubState2 : Continue
}
State2 -up-> State3 : Continue
State3 -up-> State4 << async >> : Continue
@enduml
