# This is the GitHub action workflow we use to build, test, analyze and publish the EtAlii.Generators solution.
name: Build
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./Source
          #-Dsonar.sources=lib/
          #-Dsonar.test.exclusions=tests/**
          args: >
            -Dsonar.organization=vrenken
            -Dsonar.projectKey=EtAlii.Generators
            -Dsonar.sources=.
            -Dsonar.exclusions=/**/*.puml,/**/MyAsyncStateMachine.cs
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.tests=EtAlii.Generators.Stateless.Tests/
            -Dsonar.verbose=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}



#          .\.sonar\scanner\dotnet-sonarscanner begin /k:"EtAlii.Generators" /o:"vrenken" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          #          dotnet build EtAlii.Generators.sln
#          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
