name: Publish

on:
  push:
    branches:
      - main
      - 'release/**'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true   # Stop wasting time caching packages
  DOTNET_CLI_TELEMETRY_OPTOUT: true         # Disable sending usage data to Microsoft

jobs:
  publish:

    #runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

        # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.302

        # Versioning.
      - name: Versioning
        uses: dotnet/nbgv@master
        id: nbgv

      - name: Restore dependencies
        run: dotnet restore .\Source\EtAlii.Generators.sln
      - name: Build
        run: dotnet build --no-restore .\Source\EtAlii.Generators.sln

      # Pack.
      - name: Pack
        shell: powershell
        run: >
          dotnet pack .\Source\EtAlii.Generators.sln
          --no-restore
          /p:PackageVersion=${{ steps.nbgv.outputs.NuGetPackageVersion }}
          /p:RepositoryCommit=${{ steps.nbgv.outputs.GitCommitId }}
          /p:RepositoryType=git

      - name: Test
        run: dotnet test --no-build --verbosity normal .\Source\EtAlii.Generators.sln
      - name: Publish
        run: dotnet nuget push .\Source\**\*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_ORG_TOKEN }} --source https://api.nuget.org/v3/index.json
