name: Publish

on:
  workflow_dispatch:

jobs:
  publish:

    #runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore .\Source\EtAlii.Generators.sln
      - name: Build
        run: dotnet build --no-restore .\Source\EtAlii.Generators.sln
      - name: Test
        run: dotnet test --no-build --verbosity normal .\Source\EtAlii.Generators.sln
      - name: Publish
        run: dotnet nuget push .\Source\**\*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_ORG_TOKEN }} --source https://api.nuget.org/v3/index.json
